- name: Evaluate AMQ Streams Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'amq-streams-subscription.yml.j2') }}"

- name: Wait for AMQ Streams Operator to be Running
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: openshift-operators
    label_selectors:
      - name = amq-streams-cluster-operator
      - rht.comp = AMQ_Streams
    field_selectors:
      - status.phase=Running
  register: r_amq_streams_operator_pod
  retries: 120
  delay: 10
  until: r_amq_streams_operator_pod.resources | list | length == 1

- name: Evaluate Cluster ConfigMap
  k8s:
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('file', 'metrics-cm.yml') }}"

- name: Evaluate Cluster Instance
  k8s:
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('template', 'cluster.yml.j2') }}"

- name: Waiting for Cluster instance to be ready
  shell: set -o pipefail && oc get kafka -n {{ cluster_project }} | grep {{ kafka_cluster_name }}
  register: install_status
  until: "'True' in install_status.stdout"
  retries: 20
  delay: 15
  args:
    executable: /bin/bash

- name: Evaluate User Producer
  k8s:
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('template', 'producer-user.yml.j2') }}"

- name: Evaluate User Processor
  k8s:
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('template', 'processor-user.yml.j2') }}"

- name: Evaluate a_quotes Topic
  k8s:
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('template', 'quote-topic.yml.j2') }}"

- name: Evaluate a_quote_requests Topic
  k8s:
    state: present
    namespace: '{{ cluster_project }}'
    resource_definition: "{{ lookup('template', 'quote-request-topic.yml.j2') }}"
